FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/hzhsbsjssushs/elsa /root/hzhsbsjssushs
WORKDIR /root/hzhsbsjssushs/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
