FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/Sjshskdhd/BOT_ELSA-V2 /root/Sjshskdhd
WORKDIR /root/Sjshskdhd/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
